monitor:
  memory_threshold: 16106127360  # 15GB in bytes
  timeout: 3600  # 1 hour

database:
  path: "../../data/db/"  # Path to database files
  name: "Bupa.db"

logging:
  log_dir: "logs"  # Directory for logs

results:
  output_dir: "results"  # Directory for saving results

algorithm:
  name: "MATILDA"  # Default algorithm

mlflow:
  use: false  # Set to true to log experiments to mlflow
  tracking_uri: "http://localhost:5000"  # Example URI, update as needed
  experiment_name: "Rule Discovery Experiment"


